- name: catalogue install
  hosts: catalogue
  become: yes
  tasks:
   - name: enabling and disabling nodejs
     ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
   - name: install nodejs
     ansible.builtin.package:
      name: nodejs
      state: present
   - name: user add
     ansible.builtin.user:
      name: roboshop
   - name: create directory
     ansible.builtin.file:
      name: /app
      state: directory
   - name: install application
     ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
   - name: unzip
     ansible.builtin.unarchive:
       src: /tmp/catalogue.zip
       dest: /app
       remote_src: yes
   - name: npm install
     ansible.builtin.command: npm install
   - name: copying service
     ansible.builtin.copy:
       src: catalogue.service
       dest: /etc/systemd/system/catalogue.service
   - name: demon reload
     ansible.builtin.systemd_service:
       daemon_reload: true