- name: catalogue install
  hosts: catalogue
  become: yes
  tasks:
   - name: enable nodejs
     ansible.builtin.shell: dnf module disable nodejs -y ,dnf module enable nodejs:18 -y
   - name: install catalogue
     ansible.builtin.package:
      name: nodejs
      state: started