- name: catalogue install
  hosts: catalogue
  become: yes
  tasks:
   - name: enable nodejs
     ansible.builtin.shell: dnf module disable nodejs,dnf module enable nodejs:18 
   - name: install catalogue
     ansible.builtin.package:
      name: nodejs
      state: started