- name: catalogue install
  hosts: catalogue
  become: yes
  tasks:
   - name: enabling and disabling nodejs
     ansible.buitin.shell: dnf module disable nodejs -y;dnf module enable nodejs:18 -y 
   - name: installnodejs
     ansible.builtin.package:
      name: nodejs
      state: present
