- name: catalogue install
  hosts: catalogue
  become: yes
  tasks:
   - name: enable nodejs
     ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y 
   - name: install catalogue
     ansible.builtin.package:
      name: nodejs
      state: present
   - name: user add
     ansible.builtin.user:
      name: roboshop
   - name: make directory
     ansible.builtin.file:
      path: /app
      state: directory
   - name: download application
     ansible.builtin.get_url:
      url:  https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp   
   - name: unzip the application
     ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
   - name: npm install
     ansible.builtin.command: npm install
     

