- name: installing mongodb
  hosts: mongodb
  become: yes
  tasks: 
   - name: copying repo
     ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongodb.repo
   - name: install mongod
     ansible.builtin.package:
       name: mongodb-org
       state: present
   - name: enable and start mongod
     ansible.builtin.service:
       name: mongod
       enabled: yes
       state: started