- name: configuring mysql
  hosts: mysql
  become: yes
  tasks:
    - name: disable mysql
      ansible.builtin.shell: dnf module disable mysql -y
    - name: copying mysql.service
      ansible.builtin.copy:
       src: mysql.repo
       dest: /etc/yum.repos.d/mysql.repo
    - name: install mysql
      ansible.builtin.dnf:
       name: mysql-community-server 
       state: present
    - name: start and enable
      ansible.builtin.service:
       name: mysqld
       enabled: yes
       state: started
    - name: password change to mysql
      ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
    - name: checking password
      ansible.builtin.command: mysql -uroot -pRoboShop@1 
    