- name: configuring redis
  hosts: redis
  become: yes
  tasks: 
    - name: installing from browser
      ansible.builtin.command: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
    - name: update redis
      ansible.builtin.command: dnf module enable redis:remi-6.2 -y

    - name: installing redis
      ansible.builtin.package:
       name: redis
       state: present
