- name: configuring redis
  hosts: redis
  become: yes
  tasks: 
    - name: installing remi
      ansible.builtin.dnf:
       name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm 
       state: present
    - name: update redis
      ansible.builtin.command: dnf module enable redis:remi-6.2 -y

    - name: installing redis
      ansible.builtin.dnf:
       name: redis
       state: present
