- name: configuring redis
  hosts: redis
  become: yes
  tasks: 
    - name: installing remi
      ansible.builtin.dnf:
       name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm 
       state: present
       disable_gpg_check: true
    - name: update redis
      ansible.builtin.command: dnf module enable redis:remi-6.2 -y

    - name: installing redis
      ansible.builtin.dnf:
       name: redis
       state: present
    - name: remote changes
      ansible.builtin.replace:
       path: /etc/redis/redis.conf
       regexp: '127.0.0.1'
       replace: '0.0.0.0'
    - name: restart redis
      ansible.builtin.service:
       name: redis
       enabled: yes
       state: restarted