- name: web installation
  hosts: web
  become: yes
  tasks: 
   - name: installing nginx
     ansible.builtin.package:
      name: nginx
      state: present
   - name:  enabling and start nginx
     ansible.builtin.service:
       name: nginx
       enabled: yes
       state: started
