- name: installing nginx
  hosts: web
  become: yes
  tasks:
   - name: installing nginx
     ansible.builtin.package:
      name: nginx
      state: present
   - name: enable and start nginx
     ansible.builtin.service:
      name: nginx
      enabled: yes
      state: started
   - name: removing content
     ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent
   - name: download frontend content
     ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp/web.zip
   - name :copying into a file
     ansible.builtin.copy:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
   - name: unzip a file
     ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes      


   